export interface IUser {
    id: string,
    fullName: string,
    email: string,
    image: string,
    userName: string,
    phoneNumber: string,
    lable?: string,
    firstName?: string,
    lastName?: string,
    middleName?: string,
    fatherName?: string,
    motherName?: string,
    spouseName?: string,
    dob?: Date,
    address?: string,
    nid?: string,
    existingImage?: string,
    facebook?: string,
    linkedin?: string,
    twitter?: string,
    instragram?: string,
    github?: string,
    genderId?: number,
    genderName?: string
}